#!/bin/bash

#docker run --name="nginx" -ti  -p 8080:80   \
docker run --name="nginx" -d -p 8080:80    \
           -v /var/sotolito/vols/nginx/var:/var/ \
           -v /var/sotolito/vols/nginx/etc/nginx:/etc/nginx \
           -v /var/sotolito/vols/nginx/usr/share/nginx/:/usr/share/nginx/ \
           -v /var/sotolito/vols/php-fpm/run/php-fpm/:/run/php-fpm/  \
           -v /var/sotolito/vols/php-apps/:/usr/share/nginx/html/php-apps/ \
           -e "LANG=en_US.UTF-8" \
           -e "LC_MESSAGES=POSIX" \
           -e "LANGUAGE=en_US.UTF-8" \
           -e "LC_CTYPE=en_US.UTF-8" \
           sotolitolabs-cubie/nginx  \



